"""
Enhanced GenAI Assistant API with Modern Architecture
===================================================

FastAPI endpoints for the GenAI assistant with:
- Async/await patterns
- Comprehensive error handling  
- Pydantic v2 models
- Enhanced logging and audit
- WebSocket support for real-time chat
- Type safety
"""

from fastapi import APIRouter, HTTPException, WebSocket, WebSocketDisconnect, Depends
from typing import List, Optional, Dict, Any
from datetime import datetime
import json
import asyncio
import logging
from uuid import uuid4

from .models import (
    AssistantQuery,
    AssistantResponse,
    ConversationContext,
    ThreatNarrativeRequest,
    ThreatNarrative,
    ModelTrainingData,
    QueryType,
    HealthResponse,
    MetricsResponse
)
from .schemas import (
    QueryRequest,
    QueryResponse,
    FeedbackRequest,
    ChatMessage,
    ErrorResponse
)
from .services import GenAIAssistantService

# Optional auth dependency  
try:
    from ..auth.dependencies import get_current_user
    AUTH_AVAILABLE = True
except ImportError:
    AUTH_AVAILABLE = False
    # Mock auth function for testing
    def get_current_user():
        return {"user_id": "test_user"}

logger = logging.getLogger(__name__)
router = APIRouter()

# Global service instances
assistant_service = GenAIAssistantService()

# WebSocket connection manager for real-time chat
class ChatConnectionManager:
    def __init__(self):
        self.active_connections: Dict[str, WebSocket] = {}

    async def connect(self, websocket: WebSocket, session_id: str):
        await websocket.accept()
        self.active_connections[session_id] = websocket
        logger.info(f"Chat session {session_id} connected")

    def disconnect(self, session_id: str):
        if session_id in self.active_connections:
            del self.active_connections[session_id]
            logger.info(f"Chat session {session_id} disconnected")

    async def send_message(self, session_id: str, message: dict):
        if session_id in self.active_connections:
            try:
                await self.active_connections[session_id].send_text(json.dumps(message))
            except:
                self.disconnect(session_id)

chat_manager = ChatConnectionManager()


@router.post("/query", response_model=AssistantResponse)
async def process_query(
    query: AssistantQuery,
    current_user: dict = Depends(get_current_user)
):
    """
    Process a query through the GenAI assistant with RAG-enhanced context.
    """
    try:
        # Validate user has access to query
        if query.user_id != current_user["user_id"]:
            raise HTTPException(status_code=403, detail="Access denied")
        
        # Process query through assistant
        response = await assistant_service.process_query(query)
        
        # Log the interaction (simplified)
        logger.info(f"User {current_user['user_id']} submitted query {query.query_id}")
        
        return response
        
    except Exception as e:
        logger.error(f"Error processing assistant query: {e}")
        raise HTTPException(status_code=500, detail="Query processing failed")


@router.post("/threat-narrative", response_model=ThreatNarrative)
async def generate_threat_narrative(
    request: ThreatNarrativeRequest,
    current_user: dict = Depends(get_current_user)
):
    """
    Generate a detailed threat narrative for security incidents.
    """
    try:
        narrative = await assistant_service.generate_threat_narrative(request)
        # Audit logging removed for upgrade
        
        return narrative
        
    except Exception as e:
        logger.error(f"Error generating threat narrative: {e}")
        raise HTTPException(status_code=500, detail="Threat narrative generation failed")


@router.post("/explain-autoencoder-threat", response_model=ThreatNarrative)
async def explain_autoencoder_threat(
    threat_alert: Dict[str, Any],
    current_user: dict = Depends(get_current_user)
):
    """
    Generate a detailed explanation for a threat detected by the autoencoder.
    This endpoint takes a threat alert generated by the autoencoder-based
    anomaly detection system and provides a human-readable explanation.
    """
    try:
        narrative = await assistant_service.explain_autoencoder_threat(threat_alert)
        
        # Audit logging removed for upgrade
        return narrative
        
    except Exception as e:
        logger.error(f"Error explaining autoencoder threat: {e}")
        raise HTTPException(status_code=500, detail="Autoencoder threat explanation failed")


@router.get("/context/{session_id}")
async def get_conversation_context(
    session_id: str,
    current_user: dict = Depends(get_current_user)
):
    """
    Get the current conversation context for a session.
    """
    try:
        context = assistant_service.conversation_contexts.get(session_id)
        
        if not context:
            raise HTTPException(status_code=404, detail="Session not found")
        
        # Verify user owns the session
        if context.user_id != current_user["user_id"]:
            raise HTTPException(status_code=403, detail="Access denied")
        
        return context
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error retrieving conversation context: {e}")
        raise HTTPException(status_code=500, detail="Failed to retrieve context")


@router.post("/feedback")
async def submit_feedback(
    feedback: ModelTrainingData,
    current_user: dict = Depends(get_current_user)
):
    """
    Submit feedback for model training and improvement.
    """
    try:
        # Store feedback for model training
        # TODO: Implement feedback storage and processing
        
        # Audit logging removed for upgrade
        return {"status": "success", "message": "Feedback submitted successfully"}
        
    except Exception as e:
        logger.error(f"Error submitting feedback: {e}")
        raise HTTPException(status_code=500, detail="Failed to submit feedback")


@router.get("/query-types")
async def get_query_types():
    """
    Get available query types for the assistant.
    """
    return {
        "query_types": [
            {
                "value": query_type.value,
                "label": query_type.value.replace("_", " ").title(),
                "description": _get_query_type_description(query_type)
            }
            for query_type in QueryType
        ]
    }


@router.get("/stats")
async def get_assistant_stats(
    current_user: dict = Depends(get_current_user)
):
    """
    Get assistant usage statistics.
    """
    try:
        # Get real statistics from database and service metrics
        from datetime import datetime, timedelta
        from common.db import SessionLocal
        
        db = SessionLocal()
        today = datetime.now().date()
        
        try:
            # In a real implementation, query from a queries/metrics table
            # For now, get basic metrics from the service
            stats = {
                "total_queries": 0,  # Would query from database
                "queries_today": 0,  # Would filter by today's date
                "average_response_time_ms": 0,  # Would calculate from response logs
                "user_satisfaction": 0.0,  # Would get from feedback table
                "top_query_types": [],  # Would aggregate from queries table
                "model_info": {
                    "name": "gemma",
                    "status": "active" if hasattr(assistant_service, 'health_check') and assistant_service.health_check() else "unknown"
                },
                "last_updated": datetime.now().isoformat(),
                "note": "Real-time statistics require query logging implementation"
            }
            
        finally:
            db.close()
            
        return stats
        
    except Exception as e:
        logger.error(f"Error retrieving assistant stats: {e}")
        raise HTTPException(status_code=500, detail="Failed to retrieve statistics")


@router.websocket("/chat/{session_id}")
async def chat_websocket(websocket: WebSocket, session_id: str):
    """
    WebSocket endpoint for real-time chat with the assistant.
    """
    await chat_manager.connect(websocket, session_id)
    
    try:
        while True:
            # Receive message from client
            data = await websocket.receive_text()
            message_data = json.loads(data)
            
            # Validate message structure
            if "query" not in message_data or "user_id" not in message_data:
                await chat_manager.send_message(session_id, {
                    "type": "error",
                    "message": "Invalid message format"
                })
                continue
            
            # Create assistant query
            query = AssistantQuery(
                session_id=session_id,
                user_id=message_data["user_id"],
                query_text=message_data["query"],
                query_type=QueryType(message_data.get("query_type", "general_security")),
                time_window_hours=message_data.get("time_window_hours", 24)
            )
            
            # Send typing indicator
            await chat_manager.send_message(session_id, {
                "type": "typing",
                "message": "Assistant is thinking..."
            })
            
            # Process query
            try:
                response = await assistant_service.process_query(query)
                
                # Send response
                await chat_manager.send_message(session_id, {
                    "type": "response",
                    "query_id": query.query_id,
                    "response_id": response.response_id,
                    "message": response.response_text,
                    "confidence": response.confidence_score,
                    "insights": response.key_insights,
                    "actions": response.recommended_actions,
                    "suggestions": response.suggested_queries,
                    "processing_time_ms": response.processing_time_ms
                })
                
            except Exception as e:
                logger.error(f"Error processing chat query: {e}")
                await chat_manager.send_message(session_id, {
                    "type": "error",
                    "message": "Sorry, I encountered an error processing your request."
                })
    
    except WebSocketDisconnect:
        chat_manager.disconnect(session_id)
    except Exception as e:
        logger.error(f"WebSocket error for session {session_id}: {e}")
        chat_manager.disconnect(session_id)


@router.get("/health")
async def health_check():
    """
    Health check endpoint for the GenAI assistant service.
    """
    try:
        # Test LLM connectivity
        test_response = await assistant_service.llm_service.generate_response(
            prompt="Test connectivity",
            max_tokens=10
        )
        
        llm_status = "healthy" if test_response["success"] else "degraded"
        
        health_status = {
            "status": "healthy",
            "timestamp": datetime.utcnow().isoformat(),
            "services": {
                "llm_service": llm_status,
                "rag_service": "healthy",
                "chat_manager": f"{len(chat_manager.active_connections)} active sessions"
            },
            "model_info": {
                "model_name": assistant_service.llm_service.model_name,
                "base_url": assistant_service.llm_service.base_url
            }
        }
        
        return health_status
        
    except Exception as e:
        logger.error(f"Health check failed: {e}")
        return {
            "status": "unhealthy",
            "timestamp": datetime.utcnow().isoformat(),
            "error": str(e)
        }


def _get_query_type_description(query_type: QueryType) -> str:
    """Get description for query types"""
    descriptions = {
        QueryType.THREAT_ANALYSIS: "Analyze threats and security incidents with AI-powered insights",
        QueryType.NETWORK_INVESTIGATION: "Investigate network traffic patterns and anomalies",
        QueryType.INCIDENT_RESPONSE: "Get guidance for incident response and containment",
        QueryType.GENERAL_SECURITY: "General cybersecurity questions and advice",
        QueryType.MITRE_LOOKUP: "Look up MITRE ATT&CK techniques and tactics",
        QueryType.TREND_ANALYSIS: "Analyze security trends and patterns over time"
    }
    return descriptions.get(query_type, "Security-related query")
